# Build settings
gems:
  - jemoji
  - jekyll-paginate

# Site settings
title: "Opinion by Inverse Lattice"
description: > # this means to ignore newlines until "email:"
   A platform for educated idiots.

email: mrsauravs@gmail.com
#blog logo
logo: "/assets/images/df_logo.jpg"
float_logo: true # true, false (default)

# blog cover
cover: "/assets/images/cA4aKEIPQrerBnp1yGHv_IMG_9534-3-2.jpg"

name: 'Saurabh Sugandh'
author: 'Saurabh Sugandh'
author_image: "/assets/images/author.jpg"

paginate:	5

url: "https://mrsauravs.github.io" # the base hostname & protocol for your site
baseurl: "/opinion"
#used to display twitter cards
twitter_handle: '@sugandh_saurabh'

#fill in disqus shortname to use disqus
disqus: inverselattice

#google_analytics: UA-XXXXX-X

# social icons and sharing options
social:
  - icon:	twitter
    url:	https://twitter.com/sugandh_saurabh
    desc: Follow me on twitter
    share_url: http://twitter.com/share
    share_title: ?text=
    share_link: "&amp;url="

#  - icon:	facebook
#    url:	https://facebook.com/???
#    desc: Connect with me facebook
#    share_url: https://www.facebook.com/sharer.php
#    share_title: ?t=
#    share_link: "&amp;u="

  - icon:	github
    url:	https://github.com/mrsauravs
    desc:	Fork me on github
    share_url:
    share_title:
    share_link:

